image:
  file: .gitpod.Dockerfile

tasks:
  - init:
      cd api &&
      npm install &&
      cd ../app &&
      npm install &&
      cd .. &&
      npm install

vscode:
  extensions:
    - ms-azuretools.vscode-azurefunctions


