name: Deploy App (Web)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Api
        run: |
          npm install
          npm run build:github
          npm pack
        working-directory: api
      - name: Build Azure Api
        run: |
          npm uninstall knightlife-api
          npm install ../api/knightlife-api-*.tgz
          npm install
          npm run build:github
        working-directory: azure-api
      - name: Build React Native App
        run: |
          npm uninstall knightlife-api
          npm install ../api/knightlife-api-*.tgz
          npm install
          npm run build:github
        working-directory: react-native-app
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "react-native-app"
          api_location: "azure-api"
          output_location: "web-build"
          skip_app_build: true
          skip_api_build: true
        env:
          OPEN_BANKING_USE_SANDBOX: false
